FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-runtime
RUN apt-get update && apt-get install -yq git libgl1 libglib2.0-0 libsm6 libxrender1 libxext6
RUN pip install opencv-python git+https://github.com/facebookresearch/segment-anything.git

RUN pip install \
    fastapi==0.101.0 \
    pydantic==2.1.1 \
    websockets==10.4 \
    httpx==0.25.0 \
    exceptiongroup==1.1.3 \
    anyio==4.0.0 \
    uvicorn==0.20.0 \
    python-multipart==0.0.6 \
    pyyaml==5.3.1

CMD /bin/bash